# Generated by Django 4.2.7 on 2023-12-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctor_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
