# Generated by Django 4.2.7 on 2023-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
