# Generated by Django 4.2.7 on 2023-12-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_doctor_end_time_doctor_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Special',
            new_name='Specialization',
        ),
    ]
