# Generated by Django 4.2.7 on 2023-12-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_doctor_login_delete_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
