# Generated by Django 4.2.7 on 2023-12-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_user',
        ),
    ]
