# Generated by Django 4.2.7 on 2023-12-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_registration_delete_login_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
